### ISSUE TITLE
Wireframe init requires navigationController not viewController as current

### ISSUE THREAD

**Issue by Adis** [infinum/iOS-VIPER-Xcode-Templates#10]
Another SS:
https://scr.infinum.co/adis/SettingsWireframe.swift__Edited_2018-03-23_11-56-10.png

**Comment by infinum-ios** [comment]
This happened because you were using v1 base classes and v2 template. Since v2 introduced breaking changes, do you think we should rename base classes and templates in v1 or in v2?

**Comment by Truba** [comment]
This happened because you were using v1 base classes and v2 template. Since v2 introduced breaking changes, do you think we should rename base classes and templates in v1 or in v2?

**Comment by Adis** [comment]
Nah, let's leave it as it is atm.
