### ISSUE TITLE
ModuleViewController generation without Storyboard

### ISSUE THREAD

**Issue by michaelcordero** [infinum/iOS-VIPER-Xcode-Templates#13]
Please make VIPER modules have an option to generate without the use of UIStoryboard. I've found that compile times are much quicker without storyboards.

**Comment by vburojevic** [comment]
Hi @michaelcordero! You can always just delete the storyboard constant and initialize the view controller however you like in the wireframe. Does that answer your question?

**Comment by michaelcordero** [comment]
Yes, of course I realized that after making this comment. :+1: 
 I do have other questions. 
1. In this repo, it says an example project will be created. Where is it?
2. Should ViewInterfaces expose their properties, so that the Presenter will have access to, UI Components for example?
3. How is data to be passed through the architecture? I can point you to my current repo, so you can see code examples of what I mean...

**Comment by vburojevic** [comment]
1. It's not finished yet, PR is in progress in #12 
2. You should update view via functions exposed to presenter (for example `func setTitle(_ title: String)`)
3. Yes, it's passed via wireframes. You can add your parameters in wireframe's `init`, and pass them to presenter via it's `init` as well.

**Comment by vburojevic** [comment]
👍
