### ISSUE TITLE
How to handle the communication between the two modules ?

### ISSUE THREAD

**Issue by chris118** [infinum/iOS-VIPER-Xcode-Templates#16]
The VIPER is great and I have 2 questions: 
1. WireFrameA hold the reference WireFameB, how to decouple it ?
2. How ModuleA can pass the parameters to ModuleB and ModuleA can listen some callback from ModuleB? Where the action can be done? WireFrameA <------>WireframeB ?

**Comment by vburojevic** [comment]
1. Wireframe shouldn't hold a reference to another wireframe, can you give me an example what are you trying to do?
2. You can pass parameters (for example some action handler block, or a delegate) in wireframe's init, and then pass them to presenter's init.

**Comment by chris118** [comment]
```
// MARK: - Extensions -

extension LoginWireframe: LoginWireframeInterface {

    func navigate(to option: LoginNavigationOption) {
        switch option {
        case .home:
            _openHome()
        }
    }
    
    private func _openHome() {
        let wireframe = HomeWireframe()
        
        navigationController?.pushWireframe(wireframe)
    }

}
```

LoginWireframe hold a reference to HomeWireframe? If Login module use many other modules, Login module have to hold them, they are coupled

**Comment by vburojevic** [comment]
@chris118 in this case, navigationController holds a reference to the home view controller, and that means the whole module won't be deallocated until it popped from the stack. This is fine, that's the desired way of usage.
