### ISSUE TITLE
Implementing multiple UINavigationControllers for UITabbarController

### ISSUE THREAD

**Issue by dev-dubaisoftwaresolutions** [infinum/iOS-VIPER-Xcode-Templates#23]
I have a TabbarController and each of the tab should have their own UINavigationControllers. 
How to implement it with VIPER? Because each of the init method of each Wireframe assumes there had already been a navigationController provided.

**Comment by Truba** [comment]
Hi @dev-dubaisoftwaresolutions ,
Sry for taking me this long to respond to this question.
When I create UITabBarControllers I usually do it like this:
```swift
final class TabbarWireframe: BaseWireframe {

    init() {
        let moduleViewController = UITabBarController()//Or your subclass of UITabBarController
        super.init(viewController: moduleViewController)
        
        moduleViewController.viewControllers = [
            HomeWireframe(),
            ProfileWireframe(),
        ].map {
            UINavigationController(rootViewController: $0.viewController)
        }
    }
}
``` 
I've simplified my code a bit just to reduce the noise. But the main idea is to first create tab wireframes, and then embed their view controllers in UINavigationControllers. And finally pass those UINavigationControllers to the UITabBarController.

I'm sry, I wasn't really sure what you meant my: 

> Because each of the init method of each Wireframe assumes there had already been a navigationController provided.

But I hope I was of some help. 
Please feel free to contacts as again if you need some extra help.
Hopefully it won't take me this long to answer. 😄
