### ISSUE TITLE
Question about Presenter Template...

### ISSUE THREAD

**Issue by JCarangoH** [infinum/iOS-VIPER-Xcode-Templates#25]
Why the presenter template imports UIKit, since presenter has to be UIKit independant?

**Comment by fgulan** [comment]
We mostly left it because of UIAlertAction/UIColor/UIImage usage in Presenter but we are in discussion to use just `Foundation`

**Comment by Truba** [comment]
Should we remove `import UIKit` dependency from `Presenter` template and replace it with `import Foundation`?
/polls 'Yes' 'No'
