### ISSUE TITLE
Rename of configure in ViewController in RxModule

### ISSUE THREAD

**Issue by Truba** [infinum/iOS-VIPER-Xcode-Templates#30]
https://github.com/infinum/iOS-VIPER-Xcode-Templates/blob/423c630d98b80d5663f34044c46c0018d95f4455/Templates/Resources/Templates/___FILEBASENAME___ViewController.swift.erb#L48

What should we rename this function name in ViewController?

1)  `configure` (leave as is)
2) `configureIO`
3) `setupView`
4) Add your own idea 😄 

[![](https://api.gh-polls.com/poll/01E121NYSDHTZ3SSGAB368WWN7/configure)](https://api.gh-polls.com/poll/01E121NYSDHTZ3SSGAB368WWN7/configure/vote)
[![](https://api.gh-polls.com/poll/01E121NYSDHTZ3SSGAB368WWN7/configureIO)](https://api.gh-polls.com/poll/01E121NYSDHTZ3SSGAB368WWN7/configureIO/vote)
[![](https://api.gh-polls.com/poll/01E121NYSDHTZ3SSGAB368WWN7/setupView)](https://api.gh-polls.com/poll/01E121NYSDHTZ3SSGAB368WWN7/setupView/vote)

**Comment by vburojevic** [comment]
`bindView` 😱

**Comment by Truba** [comment]
It seems that the winner is `setupView`.
I'll create a PR with that.
