### ISSUE TITLE
Customizing base classes

### ISSUE THREAD

**Issue by HosseinArabbeigi** [infinum/iOS-VIPER-Xcode-Templates#34]
Thanks for great viper implementation.

I want to have `BasePresenter `class and `BaseInteractor ` class like `BaseWireFrame` to add some base stuffs, is there any way to make sure generated interactors and presenters are extending from my new base classes?

**Comment by Truba** [comment]
Hi @HosseinArabbeigi ,

To do something like that what you need to do is, to update the template files, for example for presenter:
https://github.com/infinum/iOS-VIPER-Xcode-Templates/blob/master/Templates/Resources/Templates/___FILEBASENAME___Presenter.swift.erb#L17
Just add:
`final class ___VARIABLE_moduleName___Presenter: YourBasePresenter {`

Then run `ruby main.rb` in terminal to to regenerate all the xocde templates.

And that's it. 
Add your templates to the xcode by calling `make install_templates` as you would normally do.

Hope this helps

**Comment by HosseinArabbeigi** [comment]
Hi @Truba 
Thanks for your response.
I did it by direct editing of xcode templates.
