### ISSUE TITLE
UITabBar support

### ISSUE THREAD

**Issue by sheharyar-rr** [infinum/ios-viper-xcode-templates#51]
I had tab bar support manually added to previous version but if it could be added natively to this repository that would be great

**Comment by kvaljeva** [comment]
Hi there! Could you please elaborate a bit more on what do you exactly mean when you say tab bar support? We usually have one module that's a TabBar which then serves and the root for everything else in the app.

I'd be happy if you'd share more information with us about, then we can see whether we can do anything about it.

**Comment by Scankiran** [comment]
Could you give an example of how can we use tabbar? If you can, I'll really appreciate it. Thanks.

**Comment by Scankiran** [comment]
I found a solution on the closed issues page. You can check this issue.

https://github.com/infinum/iOS-VIPER-Xcode-Templates/issues/23

**Comment by goranbrl** [comment]
Closing this one since the solution was linked in the previous replies.
