### ISSUE TITLE
Interactor example

### ISSUE THREAD

**Issue by Sweefties** [infinum/iOS-VIPER-Xcode-Templates#7]
Please, could you give the better way to integrate with Interactor?
Thanks ;)

**Comment by vburojevic** [comment]
Hi @Sweefties! Can you explain a bit in more details? Not sure if I understand correctly.

**Comment by Sweefties** [comment]
Hi @vburojevic , 
I would like to manage all business logic for data (ws/realm..) by interactor and populate a tableView or something else. But I'm not sure where and how to manage interactor with view controller, interface, interface and presenter classes/protocols.

**Comment by vburojevic** [comment]
Interactor would be responsible for fetching the data from the database. Presenter would be data source for view controller, and ask interactor for data, and after it fetches it, it would tell the view to reload.

Maybe it would be a good idea that we create a simple sample project with basic VIPER usages when we catch some time. Would that be helpful to you?

**Comment by Sweefties** [comment]
Yes, thanks ;)

**Comment by vburojevic** [comment]
@Sweefties  example project is now included, you can find it in Demo folder! :)
